#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mysql_ready() {
python << END
import sys
import mysql.connector

try:
    connection = mysql.connector.connect(
        password="${MYSQL_ROOT_PASSWORD}",
  
    )
except mysql.connector.Error:
    sys.exit(-1)
sys.exit(0)
END
}

until mysql_ready; do
 >&2 echo "Waiting for MySQL to become available....:-("
 sleep 1
done
 >&2 echo "MySQL is ready!!!!...:-)"

exec "$@"
